server:
    port: 8081
spring:
    datasource:
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://127.0.0.1:5432/techdev_oauth
        username:
        password:
    thymeleaf:
        cache: false
trackr:
    pageRedirectUris: http://localhost:9090/authorize
proxy:
    path: http://localhost

techdev:
    portal:
        google:
            client-id:
            client-secret:
            redirect-uri: http://localhost:8081/login
            token-url: https://accounts.google.com/o/oauth2/auth